import uuid
from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query, Path
from fastapi.responses import StreamingResponse
from sqlalchemy.orm import Session
from pydantic import BaseModel

from app.api.deps import get_current_user
from app.db.models.user import User
from app.service.agent.service import chat_with_agent, stream_chat_with_agent
from app.dependencies import get_db
from app.crud import agent as agent_crud
from app.schemas.agent import AgentSession, AgentSessionCreate, AgentSessionUpdate, AgentMessage

router = APIRouter()

class ChatRequest(BaseModel):
    message: str
    session_id: str | None = None
    stream: bool = False
    connection_id: str | None = None
    model_name: str | None = None

class ChatResponse(BaseModel):
    response: str
    session_id: str

@router.post("/chat", summary="与智能相册助手对话")
def chat_endpoint(
    request: ChatRequest,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    处理与 TrailSnap Agent 的对话请求。
    如果 session_id 未提供，将自动生成一个新的。
    """
    session_id = request.session_id or str(uuid.uuid4())
    
    # Ensure session exists
    session = agent_crud.get_session(db, session_id)
    if not session:
        session_create = AgentSessionCreate(
            id=uuid.UUID(session_id),
            title="New Chat",  # This could be generated by AI later
            status="active"
        )
        agent_crud.create_session(db, obj_in=session_create, user_id=current_user.id)

    try:
        if request.stream:
            # 返回流式响应
            return StreamingResponse(
                stream_chat_with_agent(
                    user_id=str(current_user.id),
                    session_id=session_id,
                    user_input=request.message,
                    db=db,
                    connection_id=request.connection_id,
                    model_name=request.model_name
                ),
                media_type="text/event-stream"
            )
        else:
            reply = chat_with_agent(
                user_id=str(current_user.id),
                session_id=session_id,
                user_input=request.message,
                db=db,
                connection_id=request.connection_id,
                model_name=request.model_name
            )
            return ChatResponse(response=reply, session_id=session_id)
    except ValueError as ve:
        # 捕获由于未配置 LLM 引起的异常
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"内部错误: {str(e)}")

@router.get("/sessions", response_model=List[AgentSession], summary="获取所有会话")
def get_sessions(
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=100),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    获取当前用户的所有会话列表。
    """
    return agent_crud.get_sessions_by_user(db, user_id=current_user.id, skip=skip, limit=limit)

@router.post("/sessions", response_model=AgentSession, summary="创建新会话")
def create_session(
    session_in: AgentSessionCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    创建一个新的对话会话。
    """
    return agent_crud.create_session(db, obj_in=session_in, user_id=current_user.id)

@router.delete("/sessions/{session_id}", summary="删除会话")
def delete_session(
    session_id: str = Path(..., description="The ID of the session to delete"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    删除指定的会话及其所有消息。
    """
    session = agent_crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if str(session.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to delete this session")
        
    success = agent_crud.delete_session(db, session_id)
    if not success:
        raise HTTPException(status_code=500, detail="Failed to delete session")
    return {"message": "Session deleted successfully"}

@router.put("/sessions/{session_id}/pin", response_model=AgentSession, summary="置顶/取消置顶会话")
def pin_session(
    is_pinned: bool = Query(..., description="True to pin, False to unpin"),
    session_id: str = Path(..., description="The ID of the session"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    置顶或取消置顶指定的会话。
    """
    session = agent_crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if str(session.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to modify this session")
        
    session_update = AgentSessionUpdate(is_pinned=is_pinned)
    return agent_crud.update_session(db, db_obj=session, obj_in=session_update)

@router.get("/sessions/{session_id}/messages", response_model=List[AgentMessage], summary="获取会话消息")
def get_session_messages(
    session_id: str = Path(..., description="The ID of the session"),
    skip: int = Query(0, ge=0),
    limit: int = Query(100, ge=1, le=1000),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    获取指定会话的所有消息。
    """
    session = agent_crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if str(session.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to view this session")
        
    return agent_crud.get_messages_by_session(db, session_id, skip=skip, limit=limit)

@router.delete("/messages", summary="删除会话的消息")
def delete_messages(
    session_id: str = Query(..., description="The ID of the session"),
    message_ids: str = Query(None, description="Comma-separated list of message IDs to delete"),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """
    删除指定会话的全部或部分消息。
    """
    session = agent_crud.get_session(db, session_id)
    if not session:
        raise HTTPException(status_code=404, detail="Session not found")
    if str(session.user_id) != str(current_user.id):
        raise HTTPException(status_code=403, detail="Not authorized to modify this session")
        
    if message_ids:
        ids_list = [int(i.strip()) for i in message_ids.split(",") if i.strip().isdigit()]
        if ids_list:
            from app.db.models.agent import AgentMessage as DBAgentMessage
            db.query(DBAgentMessage).filter(
                DBAgentMessage.session_id == session.id,
                DBAgentMessage.id.in_(ids_list)
            ).delete(synchronize_session=False)
            db.commit()
    else:
        success = agent_crud.delete_messages_by_session(db, session_id)
    return {"message": "Messages deleted successfully"}
