"""add users table

Revision ID: 06ce8a56658b
Revises: b802bd9b9d3b
Create Date: 2026-03-04 22:46:59.743661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ce8a56658b'
down_revision: Union[str, None] = 'b802bd9b9d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('last_failed_login', sa.DateTime(), nullable=True),
    sa.Column('lockout_until', sa.DateTime(), nullable=True),
    sa.Column('security_question', sa.String(), nullable=True),
    sa.Column('security_answer_hash', sa.String(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('albums', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_albums_owner_id'), 'albums', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'albums', 'users', ['owner_id'], ['id'])
    op.add_column('face_identities', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_face_identities_owner_id'), 'face_identities', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'face_identities', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('flight_tickets', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_flight_tickets_owner_id'), 'flight_tickets', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'flight_tickets', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('index_logs', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_index_logs_owner_id'), 'index_logs', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'index_logs', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('photo_tags', sa.Column('type', sa.String(length=50), nullable=True))
    op.add_column('photo_tags', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_photo_tags_owner_id'), 'photo_tags', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'photo_tags', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('photos', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_photos_owner_id'), 'photos', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'photos', 'users', ['owner_id'], ['id'])
    op.add_column('scenes', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_scenes_owner_id'), 'scenes', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'scenes', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tasks_owner_id'), 'tasks', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.add_column('train_tickets', sa.Column('owner_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_train_tickets_owner_id'), 'train_tickets', ['owner_id'], unique=False)
    op.create_foreign_key(None, 'train_tickets', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'train_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_train_tickets_owner_id'), table_name='train_tickets')
    op.drop_column('train_tickets', 'owner_id')
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_owner_id'), table_name='tasks')
    op.drop_column('tasks', 'owner_id')
    op.drop_constraint(None, 'scenes', type_='foreignkey')
    op.drop_index(op.f('ix_scenes_owner_id'), table_name='scenes')
    op.drop_column('scenes', 'owner_id')
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_index(op.f('ix_photos_owner_id'), table_name='photos')
    op.drop_column('photos', 'owner_id')
    op.drop_constraint(None, 'photo_tags', type_='foreignkey')
    op.drop_index(op.f('ix_photo_tags_owner_id'), table_name='photo_tags')
    op.drop_column('photo_tags', 'owner_id')
    op.drop_column('photo_tags', 'type')
    op.drop_constraint(None, 'index_logs', type_='foreignkey')
    op.drop_index(op.f('ix_index_logs_owner_id'), table_name='index_logs')
    op.drop_column('index_logs', 'owner_id')
    op.drop_constraint(None, 'flight_tickets', type_='foreignkey')
    op.drop_index(op.f('ix_flight_tickets_owner_id'), table_name='flight_tickets')
    op.drop_column('flight_tickets', 'owner_id')
    op.drop_constraint(None, 'face_identities', type_='foreignkey')
    op.drop_index(op.f('ix_face_identities_owner_id'), table_name='face_identities')
    op.drop_column('face_identities', 'owner_id')
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.drop_index(op.f('ix_albums_owner_id'), table_name='albums')
    op.drop_column('albums', 'owner_id')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
