"""add_index

Revision ID: 092372eeb240
Revises: f123456789ab
Create Date: 2026-03-28 22:09:05.097411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092372eeb240'
down_revision: Union[str, None] = 'f123456789ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_albums_name'), 'albums', ['name'], unique=False)
    op.create_index(op.f('ix_face_identities_identity_name'), 'face_identities', ['identity_name'], unique=False)
    op.create_index(op.f('ix_photo_tags_tag_name'), 'photo_tags', ['tag_name'], unique=False)
    op.create_index(op.f('ix_photos_file_path'), 'photos', ['file_path'], unique=False)
    op.create_index(op.f('ix_photos_filename'), 'photos', ['filename'], unique=False)
    op.create_index(op.f('ix_scenes_name'), 'scenes', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenes_name'), table_name='scenes')
    op.drop_index(op.f('ix_photos_filename'), table_name='photos')
    op.drop_index(op.f('ix_photos_file_path'), table_name='photos')
    op.drop_index(op.f('ix_photo_tags_tag_name'), table_name='photo_tags')
    op.drop_index(op.f('ix_face_identities_identity_name'), table_name='face_identities')
    op.drop_index(op.f('ix_albums_name'), table_name='albums')
    # ### end Alembic commands ###
