"""123

Revision ID: 0a3b98f751d6
Revises: 9f2944ccd13d
Create Date: 2026-01-29 23:06:47.796587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a3b98f751d6'
down_revision: Union[str, None] = '9f2944ccd13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 设置外键依赖之前先检查是否满足约束，把默认人脸ID设置为NULL
    op.execute("UPDATE face_identities SET default_face_id = NULL WHERE default_face_id NOT IN (SELECT id FROM faces)")
    op.create_foreign_key(None, 'face_identities', 'faces', ['default_face_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'face_identities', type_='foreignkey')
    # ### end Alembic commands ###
