"""add_maker_model_metadata

Revision ID: 332ee902efb6
Revises: 802490a6bc41
Create Date: 2026-01-08 13:34:01.354827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '332ee902efb6'
down_revision: Union[str, None] = '802490a6bc41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_metadata', sa.Column('make', sa.String(length=100), nullable=True))
    op.add_column('photo_metadata', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('photo_metadata', sa.Column('shooting_params', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_metadata', 'shooting_params')
    op.drop_column('photo_metadata', 'model')
    op.drop_column('photo_metadata', 'make')
    # ### end Alembic commands ###
