"""add reasoning and tool_calls to agent_messages

Revision ID: 3bceb4cf5cb0
Revises: 441989688cbf
Create Date: 2026-04-19 16:28:49.433258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bceb4cf5cb0'
down_revision: Union[str, None] = '441989688cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_messages', sa.Column('reasoning', sa.Text(), nullable=True))
    op.add_column('agent_messages', sa.Column('tool_calls', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_messages', 'tool_calls')
    op.drop_column('agent_messages', 'reasoning')
    # ### end Alembic commands ###
