"""add md5 to photo

Revision ID: 441989688cbf
Revises: 56469698510b
Create Date: 2026-04-05 12:50:37.893149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '441989688cbf'
down_revision: Union[str, None] = '56469698510b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('md5', sa.String(length=32), nullable=True))
    op.create_index(op.f('ix_photos_md5'), 'photos', ['md5'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_md5'), table_name='photos')
    op.drop_column('photos', 'md5')
    # ### end Alembic commands ###
