"""add task indexes

Revision ID: 56469698510b
Revises: 092372eeb240
Create Date: 2026-03-31 00:01:36.356182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56469698510b'
down_revision: Union[str, None] = '092372eeb240'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_tasks_status_priority_created', 'tasks', ['status', 'priority', 'created_at'], unique=False)
    op.create_index('ix_tasks_type_status', 'tasks', ['type', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_type_status', table_name='tasks')
    op.drop_index('ix_tasks_status_priority_created', table_name='tasks')
    # ### end Alembic commands ###
