"""init

Revision ID: 802490a6bc41
Revises: 
Create Date: 2026-01-08 10:18:19.448941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector

# revision identifiers, used by Alembic.
revision: str = '802490a6bc41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_identities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('identity_name', sa.String(length=500), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('default_face_id', sa.Integer(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['default_face_id'], ['faces.id'], ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('index_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_name', sa.String(length=50), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('photo_time', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.Enum('image', 'video', 'live_photo', name='filetype'), nullable=False),
    sa.Column('upload_time', sa.DateTime(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('image_type', sa.Enum('SCREENSHOT', 'CAMERA', 'OTHER', name='imagetype'), nullable=True),
    sa.Column('processed_tasks', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_photo_time'), 'photos', ['photo_time'], unique=False)
    op.create_table('system_state',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_system_state_key'), 'system_state', ['key'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('total_items', sa.Integer(), nullable=True),
    sa.Column('processed_items', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('train_tickets',
    sa.Column('id', sa.String(length=36), nullable=False, comment='票据ID（UUID）'),
    sa.Column('train_code', sa.String(length=20), nullable=False, comment='车次号（如G1920）'),
    sa.Column('departure_station', sa.String(length=50), nullable=False, comment='出发站'),
    sa.Column('arrival_station', sa.String(length=50), nullable=False, comment='到达站'),
    sa.Column('date_time', sa.DateTime(), nullable=False, comment='发车时间'),
    sa.Column('carriage', sa.String(length=10), nullable=False, comment='车厢号（如8A、12）'),
    sa.Column('seat_num', sa.String(length=10), nullable=False, comment='座位号（如12F、05下）'),
    sa.Column('berth_type', sa.String(length=10), nullable=True, comment='铺位类型（上/中/下/无）'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='票价（保留两位小数）'),
    sa.Column('seat_type', sa.String(length=20), nullable=False, comment='座位类型（一等座/二等座/商务座等）'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='乘车人姓名'),
    sa.Column('discount_type', sa.String(length=20), nullable=True, comment='优惠类型（学生票/儿童票/优惠票/全价票等）'),
    sa.Column('total_mileage', sa.DECIMAL(precision=10, scale=1), nullable=False, comment='线路里程（公里）'),
    sa.Column('total_running_time', sa.Integer(), nullable=False, comment='累计运行时间（分钟）'),
    sa.Column('stop_stations', sa.Text(), nullable=True, comment='经停站列表，JSON格式存储'),
    sa.Column('comments', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_tickets_id'), 'train_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_train_tickets_train_code'), 'train_tickets', ['train_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('albums',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover', sa.UUID(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('query_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('num_photos', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['cover'], ['photos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faces',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('face_identity_id', sa.UUID(), nullable=True),
    sa.Column('face_feature', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('face_rect', sa.JSON(), nullable=True),
    sa.Column('face_confidence', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('recognize_confidence', sa.DECIMAL(precision=5, scale=4), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['face_identity_id'], ['face_identities.id'], ),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_face_feature', 'faces', ['face_feature'], unique=False, postgresql_using='hnsw', postgresql_ops={'face_feature': 'vector_cosine_ops'})
    op.create_index('idx_face_identity_id', 'faces', ['face_identity_id'], unique=False)
    op.create_index('idx_face_photo_id', 'faces', ['photo_id'], unique=False)
    op.create_table('image_descriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_descriptions_id'), 'image_descriptions', ['id'], unique=False)
    op.create_index(op.f('ix_image_descriptions_photo_id'), 'image_descriptions', ['photo_id'], unique=False)
    op.create_table('image_vectors',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_table('ocr_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('text_score', sa.Float(), nullable=True),
    sa.Column('polygon', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ocr_results_photo_id'), 'ocr_results', ['photo_id'], unique=False)
    op.create_index(op.f('ix_ocr_results_text'), 'ocr_results', ['text'], unique=False)
    op.create_table('photo_metadata',
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('exif_info', sa.Text(), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('location_api', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('photo_id')
    )
    op.create_index('idx_location_city', 'photo_metadata', ['city'], unique=False)
    op.create_index('idx_location_country', 'photo_metadata', ['country'], unique=False)
    op.create_index('idx_location_lat_lng', 'photo_metadata', ['latitude', 'longitude'], unique=False)
    op.create_index('idx_location_province', 'photo_metadata', ['province'], unique=False)
    op.create_table('photo_tag_relations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['photo_tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('photo_id', 'tag_id', name='uq_photo_tag')
    )
    op.create_table('album_photos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('album_id', 'photo_id', name='uq_album_photo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('album_photos')
    op.drop_table('photo_tag_relations')
    op.drop_index('idx_location_province', table_name='photo_metadata')
    op.drop_index('idx_location_lat_lng', table_name='photo_metadata')
    op.drop_index('idx_location_country', table_name='photo_metadata')
    op.drop_index('idx_location_city', table_name='photo_metadata')
    op.drop_table('photo_metadata')
    op.drop_index(op.f('ix_ocr_results_text'), table_name='ocr_results')
    op.drop_index(op.f('ix_ocr_results_photo_id'), table_name='ocr_results')
    op.drop_table('ocr_results')
    op.drop_table('image_vectors')
    op.drop_index(op.f('ix_image_descriptions_photo_id'), table_name='image_descriptions')
    op.drop_index(op.f('ix_image_descriptions_id'), table_name='image_descriptions')
    op.drop_table('image_descriptions')
    op.drop_index('idx_face_photo_id', table_name='faces')
    op.drop_index('idx_face_identity_id', table_name='faces')
    op.drop_index('idx_face_feature', table_name='faces', postgresql_using='hnsw', postgresql_ops={'face_feature': 'vector_cosine_ops'})
    op.drop_table('faces')
    op.drop_table('albums')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_train_tickets_train_code'), table_name='train_tickets')
    op.drop_index(op.f('ix_train_tickets_id'), table_name='train_tickets')
    op.drop_table('train_tickets')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_system_state_key'), table_name='system_state')
    op.drop_table('system_state')
    op.drop_index(op.f('ix_photos_photo_time'), table_name='photos')
    op.drop_table('photos')
    op.drop_table('photo_tags')
    op.drop_table('index_logs')
    op.drop_table('face_identities')
    # ### end Alembic commands ###
