"""add_ticket_photoid

Revision ID: 8a99de383ac5
Revises: 9136754cc2a3
Create Date: 2026-01-19 23:00:34.512641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a99de383ac5'
down_revision: Union[str, None] = '9136754cc2a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('train_tickets', sa.Column('photo_id', sa.String(length=36), nullable=True, comment='关联照片ID'))
    op.create_index(op.f('ix_train_tickets_photo_id'), 'train_tickets', ['photo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_tickets_photo_id'), table_name='train_tickets')
    op.drop_column('train_tickets', 'photo_id')
    # ### end Alembic commands ###
