"""add scene table

Revision ID: 9136754cc2a3
Revises: 332ee902efb6
Create Date: 2026-01-10 00:39:48.802045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9136754cc2a3'
down_revision: Union[str, None] = '332ee902efb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scenes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('radius', sa.Integer(), nullable=True),
    sa.Column('polygon', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('photo_metadata', sa.Column('scene_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'photo_metadata', 'scenes', ['scene_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photo_metadata', type_='foreignkey')
    op.drop_column('photo_metadata', 'scene_id')
    op.drop_table('scenes')
    # ### end Alembic commands ###
