"""add shared albums

Revision ID: 96354f1896be
Revises: 06ce8a56658b
Create Date: 2026-03-08 20:10:40.191519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96354f1896be'
down_revision: Union[str, None] = '06ce8a56658b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_shared_users',
    sa.Column('album_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('album_id', 'user_id')
    )
    op.alter_column('face_identities', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    # Custom logic: Update faces.face_rect from absolute to relative coordinates
    bind = op.get_bind()
    metadata = sa.MetaData()

    # Reflect tables to ensure we have correct schema
    try:
        faces_table = sa.Table('faces', metadata, autoload_with=bind)
        photos_table = sa.Table('photos', metadata, autoload_with=bind)

        # Select all faces with photo dimensions
        query = sa.select(
            faces_table.c.id,
            faces_table.c.face_rect,
            photos_table.c.width,
            photos_table.c.height
        ).select_from(
            faces_table.join(photos_table, faces_table.c.photo_id == photos_table.c.id)
        )

        results = bind.execute(query).fetchall()
        config_path = './data/config.json'
        import os
        if os.path.exists(config_path):
            import json
            with open(config_path, 'r') as f:
                config = json.load(f)
                p_size = config.get('image', {}).get('preview_size', 1440)
        else:
            p_size = 1440
        for row in results:
            face_id = row.id
            rect = row.face_rect
            width = row.width
            height = row.height

            # Skip invalid data
            if not rect or len(rect) != 4 or not width or not height:
                continue

            max_dim = max(width, height)
            if max_dim <= 0:
                continue

            scale = p_size / max_dim
            thumb_width = width * scale
            thumb_height = height * scale

            if thumb_width <= 0 or thumb_height <= 0:
                continue

            # Convert absolute [x1, y1, x2, y2] to relative [0-1, 0-1, 0-1, 0-1]
            x1, y1, x2, y2 = rect
            new_rect = [
                min(max(x1 / thumb_width, 0.0), 1.0),
                min(max(y1 / thumb_height, 0.0), 1.0),
                min(max(x2 / thumb_width, 0.0), 1.0),
                min(max(y2 / thumb_height, 0.0), 1.0)
            ]

            # Update the face record
            bind.execute(
                faces_table.update().where(faces_table.c.id == face_id).values(face_rect=new_rect)
            )

    except Exception as e:
        print(f"Error updating faces: {e}")
        # Consider whether to raise error or continue.
        # Usually migration should fail if data update fails.
        raise e
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('face_identities', 'is_hidden',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_table('album_shared_users')
    # ### end Alembic commands ###
