"""add image_descriptions

Revision ID: 9d99204b4d54
Revises: 96354f1896be
Create Date: 2026-03-09 21:04:50.201572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d99204b4d54'
down_revision: Union[str, None] = '96354f1896be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_descriptions', sa.Column('memory_score', sa.Float(), nullable=True))
    op.add_column('image_descriptions', sa.Column('reason', sa.Text(), nullable=True))
    op.add_column('image_descriptions', sa.Column('narrative', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_descriptions', 'narrative')
    op.drop_column('image_descriptions', 'reason')
    op.drop_column('image_descriptions', 'memory_score')
    # ### end Alembic commands ###
