"""add flight_tickets table

Revision ID: 9f2944ccd13d
Revises: b3db8760aba9
Create Date: 2026-01-29 15:30:25.293125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f2944ccd13d'
down_revision: Union[str, None] = 'b3db8760aba9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_tickets',
    sa.Column('id', sa.String(length=36), nullable=False, comment='票据ID（UUID）'),
    sa.Column('flight_code', sa.String(length=20), nullable=False, comment='航班号'),
    sa.Column('departure_city', sa.String(length=50), nullable=False, comment='出发地'),
    sa.Column('arrival_city', sa.String(length=50), nullable=False, comment='目的地'),
    sa.Column('date_time', sa.DateTime(), nullable=False, comment='出发日期时间'),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False, comment='票价'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='乘车人姓名'),
    sa.Column('total_mileage', sa.DECIMAL(precision=10, scale=1), nullable=False, comment='里程'),
    sa.Column('total_running_time', sa.Integer(), nullable=False, comment='飞行时长（分钟）'),
    sa.Column('comments', sa.Text(), nullable=True, comment='备注信息'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('photo_id', sa.String(length=36), nullable=True, comment='关联照片ID'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flight_tickets_flight_code'), 'flight_tickets', ['flight_code'], unique=False)
    op.create_index(op.f('ix_flight_tickets_id'), 'flight_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_flight_tickets_photo_id'), 'flight_tickets', ['photo_id'], unique=False)
    # op.create_foreign_key(None, 'face_identities', 'faces', ['default_face_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'face_identities', type_='foreignkey')
    op.drop_index(op.f('ix_flight_tickets_photo_id'), table_name='flight_tickets')
    op.drop_index(op.f('ix_flight_tickets_id'), table_name='flight_tickets')
    op.drop_index(op.f('ix_flight_tickets_flight_code'), table_name='flight_tickets')
    op.drop_table('flight_tickets')
    # ### end Alembic commands ###
