"""add face

Revision ID: a065d6d8e0e3
Revises: 0a3b98f751d6
Create Date: 2026-02-28 00:30:53.929708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a065d6d8e0e3'
down_revision: Union[str, None] = '0a3b98f751d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face_identities', sa.Column('is_hidden', sa.Boolean(), nullable=True))
    # 将is_hidden默认值设为False
    op.execute(
        "UPDATE face_identities SET is_hidden = false WHERE is_hidden IS NULL"
    )
    op.alter_column(
        'face_identities',
        'is_hidden',
        nullable=False,
        server_default=sa.false()
    )
    op.drop_constraint(op.f('faces_face_identity_id_fkey'), 'faces', type_='foreignkey')
    op.create_foreign_key(None, 'faces', 'face_identities', ['face_identity_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faces', type_='foreignkey')
    op.create_foreign_key(op.f('faces_face_identity_id_fkey'), 'faces', 'face_identities', ['face_identity_id'], ['id'])
    op.drop_column('face_identities', 'is_hidden')
    # ### end Alembic commands ###
