"""add cluster tables

Revision ID: a356eea37cbc
Revises: 9d99204b4d54
Create Date: 2026-03-17 22:39:46.512823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a356eea37cbc'
down_revision: Union[str, None] = '9d99204b4d54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_clusters',
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=True),
    sa.Column('cluster_type', sa.String(length=50), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_table('photo_clusters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('cluster_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cluster_id'], ['image_clusters.cluster_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photo_clusters')
    op.drop_table('image_clusters')
    # ### end Alembic commands ###
