"""add cover_id to tag

Revision ID: b21a07c0b227
Revises: 522f0c6de59e
Create Date: 2026-05-11 23:04:59.178351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import uuid
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = 'b21a07c0b227'
down_revision: Union[str, None] = '522f0c6de59e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_tags', sa.Column('cover_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'photo_tags', 'photos', ['cover_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    conn = op.get_bind()

    # 1. 删除所有没有关联照片且owner_id为空的tag
    conn.execute(sa.text("""
        DELETE FROM photo_tags
        WHERE owner_id IS NULL
        AND id NOT IN (
            SELECT DISTINCT tag_id FROM photo_tag_relations
        )
    """))

    # 2. 查询所有owner_id为空的tag
    public_tags = conn.execute(sa.text("""
        SELECT id, tag_name, type FROM photo_tags WHERE owner_id IS NULL
    """)).fetchall()

    for tag in public_tags:
        tag_id = tag[0]
        tag_name = tag[1]
        tag_type = tag[2]

        # 查找photo_tag_relations表中对应的记录，按photo的owner_id分组
        users_with_tag = conn.execute(sa.text("""
            SELECT DISTINCT p.owner_id
            FROM photo_tag_relations ptr
            JOIN photos p ON ptr.photo_id = p.id
            WHERE ptr.tag_id = :tag_id
        """), {"tag_id": tag_id}).fetchall()

        for user_row in users_with_tag:
            user_id = user_row[0]
            new_tag_id = uuid.uuid4().hex

            # 获取该用户在该标签下的第一张照片作为封面
            first_photo = conn.execute(sa.text("""
                SELECT p.id
                FROM photo_tag_relations ptr
                JOIN photos p ON ptr.photo_id = p.id
                WHERE ptr.tag_id = :tag_id AND p.owner_id = :owner_id
                LIMIT 1
            """), {"tag_id": tag_id, "owner_id": user_id}).fetchone()

            cover_id = first_photo[0] if first_photo else None

            # 为每个owner_id新建一个tag
            conn.execute(sa.text("""
                INSERT INTO photo_tags (id, tag_name, type, owner_id, cover_id, create_time, update_time, is_deleted)
                VALUES (:id, :tag_name, :type, :owner_id, :cover_id, :create_time, :update_time, :is_deleted)
            """), {
                "id": new_tag_id,
                "tag_name": tag_name,
                "type": tag_type,
                "owner_id": user_id,
                "cover_id": cover_id,
                "create_time": datetime.now(),
                "update_time": datetime.now(),
                "is_deleted": False
            })

            # 更新photo_tag_relations表的tag_id字段为新建的tag的id
            conn.execute(sa.text("""
                UPDATE photo_tag_relations
                SET tag_id = :new_tag_id
                WHERE tag_id = :old_tag_id
                AND photo_id IN (
                    SELECT id FROM photos WHERE owner_id = :owner_id
                )
            """), {
                "new_tag_id": new_tag_id,
                "old_tag_id": tag_id,
                "owner_id": user_id
            })

    # 3. 删除所有owner_id为空的tag
    conn.execute(sa.text("""
        DELETE FROM photo_tags WHERE owner_id IS NULL
    """))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_tags', 'cover_id')
    # ### end Alembic commands ###
