"""add_is_custom_to_scenes

Revision ID: b3db8760aba9
Revises: 8a99de383ac5
Create Date: 2026-01-20 22:54:38.415923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3db8760aba9'
down_revision: Union[str, None] = '8a99de383ac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('photo_metadata_scene_id_fkey'), 'photo_metadata', type_='foreignkey')
    op.create_foreign_key(None, 'photo_metadata', 'scenes', ['scene_id'], ['id'], ondelete='SET NULL')
    op.add_column('scenes', sa.Column('is_custom', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scenes', 'is_custom')
    op.drop_constraint(None, 'photo_metadata', type_='foreignkey')
    op.create_foreign_key(op.f('photo_metadata_scene_id_fkey'), 'photo_metadata', 'scenes', ['scene_id'], ['id'])
    # ### end Alembic commands ###
