"""Add index for metadata

Revision ID: eb64391bffef
Revises: f0a995211c59
Create Date: 2026-04-24 16:20:50.939248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb64391bffef'
down_revision: Union[str, None] = 'f0a995211c59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_photo_metadata_address'), 'photo_metadata', ['address'], unique=False)
    op.create_index(op.f('ix_photo_metadata_city'), 'photo_metadata', ['city'], unique=False)
    op.create_index(op.f('ix_photo_metadata_country'), 'photo_metadata', ['country'], unique=False)
    op.create_index(op.f('ix_photo_metadata_district'), 'photo_metadata', ['district'], unique=False)
    op.create_index(op.f('ix_photo_metadata_province'), 'photo_metadata', ['province'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_metadata_province'), table_name='photo_metadata')
    op.drop_index(op.f('ix_photo_metadata_district'), table_name='photo_metadata')
    op.drop_index(op.f('ix_photo_metadata_country'), table_name='photo_metadata')
    op.drop_index(op.f('ix_photo_metadata_city'), table_name='photo_metadata')
    op.drop_index(op.f('ix_photo_metadata_address'), table_name='photo_metadata')
    # ### end Alembic commands ###
