"""Add soft delete fields to Photo model

Revision ID: f0a995211c59
Revises: 3bceb4cf5cb0
Create Date: 2026-04-24 15:13:43.971598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a995211c59'
down_revision: Union[str, None] = '3bceb4cf5cb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('photos', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # 2. 把所有已有数据的 is_deleted 设置为 False
    op.execute("UPDATE photos SET is_deleted = FALSE")

    # 3. 可选：如果你想让字段以后不允许为空，打开下面这行（推荐）
    op.alter_column('photos', 'is_deleted', existing_type=sa.Boolean(), nullable=False)
    op.create_index(op.f('ix_photos_deleted_at'), 'photos', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_photos_is_deleted'), 'photos', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photos_is_deleted'), table_name='photos')
    op.drop_index(op.f('ix_photos_deleted_at'), table_name='photos')
    op.drop_column('photos', 'deleted_at')
    op.drop_column('photos', 'is_deleted')
    # ### end Alembic commands ###
