"""add agent tokens

Revision ID: f123456789ab
Revises: 351912b2c1be
Create Date: 2026-03-22 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f123456789ab'
down_revision: Union[str, None] = '351912b2c1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_tokens',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tokens_id'), 'agent_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_agent_tokens_user_id'), 'agent_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_tokens_token'), 'agent_tokens', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_tokens_token'), table_name='agent_tokens')
    op.drop_index(op.f('ix_agent_tokens_user_id'), table_name='agent_tokens')
    op.drop_index(op.f('ix_agent_tokens_id'), table_name='agent_tokens')
    op.drop_table('agent_tokens')
    # ### end Alembic commands ###
